@echo off
echo Server Starter/Stopper
echo.
echo Starting Account Server...
start	/min "" "1. Account-x64.exe"
timeout 1 > nul
echo Starting Certifier...
start	/min "" "2. Certifier-x64.exe"
timeout 1 > nul
echo Starting Database Server...
start	/min "" "3. Database-x64.exe"
timeout 2 > nul
echo Starting Core Server...
start	/min "" "4. Core-x64.exe"
timeout 2 > nul
echo Starting Login Server...
start	/min "" "5. Login-x64.exe"
timeout 1 > nul
echo Starting Cache Server...
start	/min "" "6. Cache-x64.exe"
timeout 1 > nul
echo Starting World Server...
start	/min "" "7. World-x64.exe"
timeout 1 > nul
echo.
echo To stop the server, press any key! (close this window to keep server running)
pause > nul
echo.
echo Stopping World Server...
taskkill /im "7. World-x64.exe" > nul
timeout 1 > nul
echo Stopping Cache Server...
taskkill /im "6. Cache-x64.exe" > nul
echo Stopping Login Server...
taskkill /im "5. Login-x64.exe" > nul
echo Stopping Core Server...
taskkill /im "4. Core-x64.exe" > nul
echo Stopping Database Server...
taskkill /im "3. Database-x64.exe" > nul
echo Stopping Certifier Server...
taskkill /im "2. Certifier-x64.exe" > nul
echo Stopping Account Server...
taskkill /im "1. Account-x64.exe" > nul
echo.
