QT += widgets
requires(qtConfig(treeview))

SOURCES       = MainFrame.cpp \
    CWidgetAutoSave.cpp \
    CWidgetAutoSave.cpp \
    ContinentEdit.cpp \
    ContinentEdit.cpp \
    EditCommand.cpp \
    EditCommand.cpp \
    EditFiles.cpp \
    EditFiles.cpp \
    EditInfos.cpp \
    EditInfos.cpp \
    GameElementsTree.cpp \
    GameElementsTree.cpp \
    MainEdition.cpp \
    MainEdition.cpp \
    MainFrame.cpp \
    MainFrame.cpp \
    Navigator.cpp \
    Navigator.cpp \
    NewWorld.cpp \
    NewWorld.cpp \
    ObjectEdition.cpp \
    ObjectEdition.cpp \
    ObjectProperties.cpp \
    ObjectProperties.cpp \
    Settings.cpp \
    Settings.cpp \
    TerrainEdition.cpp \
    TerrainEdition.cpp \
    View.cpp \
    View.cpp \
    WorldEditor.cpp \
    WorldEditor.cpp \
    WorldList.cpp \
    WorldList.cpp \
    WorldProperties.cpp \
    WorldProperties.cpp \
    main.cpp \
    main.cpp \
    stdafx.cpp \
    stdafx.cpp
SOURCES       = MainFrame.ui

# install
target.path = $$F:\try\ATools-0.3\WorldEditor
INSTALLS += target

RESOURCES += \
    MainFrame.qrc \
    MainFrame.qrc

FORMS += \
    ContinentEdit.ui \
    NewWorld.ui \
    ObjectProperites.ui \
    Random.ui \
    WidgetAutoSave.ui \
    WorldProperties.ui

HEADERS += \
    CWidgetAutoSave.h \
    ContinentEdit.h \
    EditCommand.h \
    GameElementsTree.h \
    MainFrame.h \
    Navigator.h \
    NewWorld.h \
    ObjectEdition.h \
    ObjectProperties.h \
    TerrainEdition.h \
    WorldEditor.h \
    WorldProperties.h \
    afxres.h \
    resource.h \
    stdafx.h

DISTFILES += \
    Resources/Icons_New/3d-select.png \
    Resources/Icons_New/3d-select2.png \
    Resources/Icons_New/Globus.png \
    Resources/Icons_New/about.png \
    Resources/Icons_New/add-file.png \
    Resources/Icons_New/all-arrow.png \
    Resources/Icons_New/all-arrow2.png \
    Resources/Icons_New/automatic.png \
    Resources/Icons_New/clipboard.png \
    Resources/Icons_New/clock.png \
    Resources/Icons_New/close-window.png \
    Resources/Icons_New/code-fork.png \
    Resources/Icons_New/copy.png \
    Resources/Icons_New/crystal.png \
    Resources/Icons_New/cursor.png \
    Resources/Icons_New/cut.png \
    Resources/Icons_New/cute-monster.png \
    Resources/Icons_New/davinci-resolve.png \
    Resources/Icons_New/define-location.png \
    Resources/Icons_New/details.png \
    Resources/Icons_New/dice.png \
    Resources/Icons_New/earth-element.png \
    Resources/Icons_New/earth-element2.png \
    Resources/Icons_New/edged-faces-display-modes.png \
    Resources/Icons_New/employee-card.png \
    Resources/Icons_New/explosion.png \
    Resources/Icons_New/external-comet-space-vitaliy-gorbachev-lineal-color-vitaly-gorbachev.png \
    Resources/Icons_New/external-mountains-summer-flatart-icons-lineal-color-flatarticons.png \
    Resources/Icons_New/external-sliders-ux-and-ui-flatart-icons-lineal-color-flatarticons.png \
    Resources/Icons_New/eye1.png \
    Resources/Icons_New/eye2.png \
    Resources/Icons_New/eye3.png \
    Resources/Icons_New/foggy-night-1.png \
    Resources/Icons_New/folder-invoices.psd \
    Resources/Icons_New/grand-canyon.png \
    Resources/Icons_New/graph.png \
    Resources/Icons_New/gravity.png \
    Resources/Icons_New/grid.png \
    Resources/Icons_New/grid2.png \
    Resources/Icons_New/grid3.png \
    Resources/Icons_New/grid4.png \
    Resources/Icons_New/ground.png \
    Resources/Icons_New/halloween-cyclop-monster.png \
    Resources/Icons_New/icon_favorites.png \
    Resources/Icons_New/icon_object.png \
    Resources/Icons_New/icon_objectFolder.png \
    Resources/Icons_New/icon_rootFolder.png \
    Resources/Icons_New/icon_terrain.png \
    Resources/Icons_New/icon_terrainFolder.png \
    Resources/Icons_New/image.png \
    Resources/Icons_New/info.png \
    Resources/Icons_New/internet-folder.png \
    Resources/Icons_New/language.png \
    Resources/Icons_New/lastfile.png \
    Resources/Icons_New/light-on.png \
    Resources/Icons_New/lock.png \
    Resources/Icons_New/move-camera.png \
    Resources/Icons_New/national-park.png \
    Resources/Icons_New/nature.png \
    Resources/Icons_New/natureLOD.png \
    Resources/Icons_New/new-post.png \
    Resources/Icons_New/paint-brush.png \
    Resources/Icons_New/partly-cloudy-day.png \
    Resources/Icons_New/plus-math.png \
    Resources/Icons_New/recurring-appointment.png \
    Resources/Icons_New/resize.png \
    Resources/Icons_New/reundo.png \
    Resources/Icons_New/save-as.png \
    Resources/Icons_New/save.png \
    Resources/Icons_New/shortcuts.png \
    Resources/Icons_New/side_view.png \
    Resources/Icons_New/sort-window.png \
    Resources/Icons_New/street-view.png \
    Resources/Icons_New/street-view2.png \
    Resources/Icons_New/sun.png \
    Resources/Icons_New/switch-camera.png \
    Resources/Icons_New/telescope.png \
    Resources/Icons_New/top_view.png \
    Resources/Icons_New/totoro.png \
    Resources/Icons_New/trash.png \
    Resources/Icons_New/treasure-chest.png \
    Resources/Icons_New/undo.png \
    Resources/Icons_New/wave-lines.png \
    Resources/Icons_New/wave-linesOnOff.png \
    Resources/Icons_New/wireframe-display-modes.png \
    Resources/Icons_New/x.png \
    Resources/Icons_New/xz.png \
    Resources/Icons_New/y.png \
    Resources/Icons_New/z.png \
    Resources/Icons_New/zoom-camera.png \
    Resources/Splashscreen_0.png \
    Resources/Splashscreen_1.png \
    Resources/Splashscreen_2.png \
    Resources/Splashscreen_3.png \
    Resources/Splashscreen_4.png \
    Resources/Splashscreen_5.png \
    Resources/WorldEditor.ico \
    Resources/WorldEditor.png \
    Resources/X.png \
    Resources/XZ.png \
    Resources/Y.png \
    Resources/Z.png \
    Resources/about.png \
    Resources/add.png \
    Resources/addObj.png \
    Resources/animate.png \
    Resources/close.png \
    Resources/copy.png \
    Resources/cut.png \
    Resources/edit.png \
    Resources/edit_continentLines.png \
    Resources/edit_continents.png \
    Resources/edit_terrainColor.png \
    Resources/edit_terrainHeight.png \
    Resources/edit_terrainWater.png \
    Resources/edit_texture.png \
    Resources/edition_light.png \
    Resources/farPlane.png \
    Resources/fill_line.png \
    Resources/fill_solid.png \
    Resources/fog.png \
    Resources/fullscreen.png \
    Resources/gametime.png \
    Resources/gravity.png \
    Resources/grid.png \
    Resources/gridLand.png \
    Resources/gridPatch.png \
    Resources/gridUnity.png \
    Resources/hide.png \
    Resources/icon_favorites.png \
    Resources/icon_object.png \
    Resources/icon_objectFolder.png \
    Resources/icon_rootFolder.png \
    Resources/icon_terrain.png \
    Resources/icon_terrainFolder.png \
    Resources/language.png \
    Resources/light.png \
    Resources/list.png \
    Resources/lock.png \
    Resources/move.png \
    Resources/moveCamera.png \
    Resources/moverNames.png \
    Resources/msgbox.png \
    Resources/new.png \
    Resources/objSelect.png \
    Resources/objectsLOD.png \
    Resources/open.png \
    Resources/paste.png \
    Resources/picture.png \
    Resources/precision.png \
    Resources/quit.png \
    Resources/random.png \
    Resources/redo.png \
    Resources/remove.png \
    Resources/resize.png \
    Resources/rotate.png \
    Resources/rotateCamera.png \
    Resources/save.png \
    Resources/save_as.png \
    Resources/set_on_land.png \
    Resources/settings.png \
    Resources/show.png \
    Resources/showAttributes.png \
    Resources/showCollision.png \
    Resources/showCtrl.png \
    Resources/showDynamicObjects.png \
    Resources/showItem.png \
    Resources/showNPC.png \
    Resources/showObjects.png \
    Resources/showRegions.png \
    Resources/showSFX.png \
    Resources/showSpawnZones.png \
    Resources/showStaticObjects.png \
    Resources/showTerrain.png \
    Resources/showWater.png \
    Resources/side_view.png \
    Resources/sky.png \
    Resources/spawnMonsters.png \
    Resources/terrainLOD.png \
    Resources/terrain_1.png \
    Resources/terrain_2.png \
    Resources/terrain_3.png \
    Resources/terrain_4.png \
    Resources/terrain_5.png \
    Resources/top_view.png \
    Resources/undo.png \
    Resources/zoomCamera.png \
    WorldEditor.rc \
    WorldEditor.vcxproj \
    WorldEditor.vcxproj.filters \
    worldeditor_de.ts \
    worldeditor_en.ts
