USE [CHARACTER_01_DBF]
GO

/****** Object:  Table [dbo].[UNLOCKED_MOTIONS_TBL]    Script Date: 20/01/2019 11:53:12 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UNLOCKED_MOTIONS_TBL](
	[serverindex] [char](2) NOT NULL,
	[m_idPlayer] [varchar](7) NOT NULL,
	[m_szUnlockedMotions] [varchar](MAX) NOT NULL
	
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [CHARACTER_01_DBF]
GO

/****** Object:  Index [UNLOCKED_MOTIONS_ID1]    Script Date: 20/01/2019 11:53:20 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNLOCKED_MOTIONS_ID1] ON [dbo].[UNLOCKED_MOTIONS_TBL]
(
	[m_idPlayer] ASC,
	[serverindex] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
GO


USE [CHARACTER_01_DBF]
GO

/****** Object:  Index [UNLOCKED_MOTIONS_TBL_ID1]    Script Date: 20/01/2019 11:53:32 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNLOCKED_MOTIONS_TBL_ID1] ON [dbo].[UNLOCKED_MOTIONS_TBL]
(
	[m_idPlayer] DESC,
	[serverindex] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


USE [CHARACTER_01_DBF]
GO

/****** Object:  Index [IDX_UNLOCKED_MOTIONS_TBLL_m_idPlayer]    Script Date: 20/01/2019 11:53:40 AM ******/
CREATE UNIQUE CLUSTERED INDEX [IDX_UNLOCKED_MOTIONS_TBLL_m_idPlayer] ON [dbo].[UNLOCKED_MOTIONS_TBL]
(
	[m_idPlayer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


USE [CHARACTER_01_DBF]
GO

/****** Object:  StoredProcedure [dbo].[SAVE_UNLOCKED_MOTIONS]    Script Date: 20/01/2019 11:53:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SAVE_UNLOCKED_MOTIONS]
	@im_idPlayer varchar(7),
	@iserverindex char(2),
	@im_szUnlockedMotions varchar(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION;

	IF EXISTS (SELECT 1 FROM UNLOCKED_MOTIONS_TBL WITH (UPDLOCK,SERIALIZABLE) WHERE m_idPlayer = @im_idPlayer AND serverindex = @iserverindex)
		UPDATE UNLOCKED_MOTIONS_TBL SET	m_szUnlockedMotions = @im_szUnlockedMotions
							 WHERE
								  m_idPlayer = @im_idPlayer
							 AND  serverindex = @iserverindex
	ELSE
		INSERT UNLOCKED_MOTIONS_TBL (m_idPlayer,     serverindex,    m_szUnlockedMotions)
					VALUES	  (@im_idPlayer, @iserverindex, @im_szUnlockedMotions)

	COMMIT TRANSACTION;
END

GO