USE [CHARACTER_01_DBF]
ALTER TABLE CHARACTER_TBL
ADD m_nHideCoat int;

GO

USE [CHARACTER_01_DBF]
UPDATE CHARACTER_TBL SET m_nHideCoat = 0 WHERE m_nHideCoat IS NULL;
ALTER TABLE CHARACTER_TBL ALTER COLUMN m_nHideCoat INTEGER NOT NULL;