/*
Read and aggregate the Titanium Phase 0 Extended Events files.
Run after stopping the session, or accept that an active file can still receive events.

The wildcard must match the rollover files generated by the event_file target.
*/

:setvar EventFileWildcard "C:\Temp\Titanium_Phase0_Baseline*.xel"
:setvar TopRows "200"

USE [master];
GO

IF OBJECT_ID('tempdb..#TitaniumPhase0SqlEvents') IS NOT NULL
    DROP TABLE #TitaniumPhase0SqlEvents;

;WITH RawEvents AS
(
    SELECT
        object_name AS event_name,
        file_name,
        file_offset,
        CONVERT(xml, event_data) AS event_xml
    FROM sys.fn_xe_file_target_read_file(
        N'$(EventFileWildcard)',
        NULL,
        NULL,
        NULL
    )
)
SELECT
    event_name,
    event_xml.value('(event/@timestamp)[1]', 'datetime2(7)') AS timestamp_utc,
    event_xml.value('(event/data[@name="duration"]/value)[1]', 'bigint') / 1000.0 AS duration_ms,
    event_xml.value('(event/data[@name="cpu_time"]/value)[1]', 'bigint') / 1000.0 AS cpu_ms,
    event_xml.value('(event/data[@name="logical_reads"]/value)[1]', 'bigint') AS logical_reads,
    event_xml.value('(event/data[@name="writes"]/value)[1]', 'bigint') AS writes,
    event_xml.value('(event/data[@name="row_count"]/value)[1]', 'bigint') AS row_count,
    event_xml.value('(event/action[@name="database_id"]/value)[1]', 'int') AS database_id,
    event_xml.value('(event/action[@name="session_id"]/value)[1]', 'int') AS session_id,
    event_xml.value('(event/action[@name="client_app_name"]/value)[1]', 'nvarchar(256)') AS client_app_name,
    event_xml.value('(event/action[@name="client_hostname"]/value)[1]', 'nvarchar(256)') AS client_hostname,
    event_xml.value('(event/action[@name="username"]/value)[1]', 'nvarchar(256)') AS username,
    COALESCE(
        NULLIF(event_xml.value('(event/action[@name="sql_text"]/value)[1]', 'nvarchar(max)'), N''),
        NULLIF(event_xml.value('(event/data[@name="statement"]/value)[1]', 'nvarchar(max)'), N''),
        NULLIF(event_xml.value('(event/data[@name="batch_text"]/value)[1]', 'nvarchar(max)'), N'')
    ) AS sql_text,
    file_name,
    file_offset
INTO #TitaniumPhase0SqlEvents
FROM RawEvents;

-- Slowest individual calls.
SELECT TOP ($(TopRows))
    timestamp_utc,
    event_name,
    DB_NAME(database_id) AS database_name,
    duration_ms,
    cpu_ms,
    logical_reads,
    writes,
    row_count,
    session_id,
    client_app_name,
    client_hostname,
    username,
    sql_text
FROM #TitaniumPhase0SqlEvents
ORDER BY duration_ms DESC, timestamp_utc ASC;

-- Highest total database cost by exact captured SQL text.
SELECT TOP ($(TopRows))
    DB_NAME(database_id) AS database_name,
    event_name,
    COUNT_BIG(*) AS call_count,
    SUM(duration_ms) AS total_duration_ms,
    AVG(duration_ms) AS average_duration_ms,
    MAX(duration_ms) AS maximum_duration_ms,
    SUM(cpu_ms) AS total_cpu_ms,
    SUM(logical_reads) AS total_logical_reads,
    SUM(writes) AS total_writes,
    SUM(row_count) AS total_row_count,
    sql_text
FROM #TitaniumPhase0SqlEvents
GROUP BY
    database_id,
    event_name,
    sql_text
ORDER BY total_duration_ms DESC, call_count DESC;

-- Workload totals per database and event type.
SELECT
    DB_NAME(database_id) AS database_name,
    event_name,
    COUNT_BIG(*) AS call_count,
    SUM(duration_ms) AS total_duration_ms,
    AVG(duration_ms) AS average_duration_ms,
    MAX(duration_ms) AS maximum_duration_ms,
    SUM(cpu_ms) AS total_cpu_ms,
    SUM(logical_reads) AS total_logical_reads,
    SUM(writes) AS total_writes,
    SUM(row_count) AS total_row_count
FROM #TitaniumPhase0SqlEvents
GROUP BY
    database_id,
    event_name
ORDER BY
    total_duration_ms DESC;
GO
