
#if !defined(AFX_WORLDSERVER_H__A8643142_CE71_4A79_A1F3_3EC998E88771__INCLUDED_)
#define AFX_WORLDSERVER_H__A8643142_CE71_4A79_A1F3_3EC998E88771__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#ifdef __LEESE_WORLDSERVER_OPT
#include <string>
#endif //__LEESE_WORLDSERVER_OPT

enum LOGTYPE
{
	LOGTYPE_TIME,
	LOGTYPE_BEFORE,
	LOGTYPE_CCU,
#ifdef __VENDING_NPC
	LOGTYPE_VENDOR,
#endif // __VENDING_NPC
	LOGTYPE_DUNGEON,
	LOGTYPE_AFTER,
	LOGTYPE_PERFOMANCE,
	LOGTYPE_RESPAWN,
	LOGTYPE_WARN1,
	LOGTYPE_WARN2,
#ifndef __LEESE_WORLDSERVER_OPT
	LOGTYPE_MAP,
#endif //__LEESE_WORLDSERVER_OPT
	LOGTYPE_MAX,
	LOGTYPE_REDRAW = LOGTYPE_MAX,
};

#ifdef __LEESE_WORLDSERVER_OPT
void SetServerList(std::string serverList);
#endif //__LEESE_WORLDSERVER_OPT

extern void SetLogInfo( LOGTYPE type, LPCTSTR lpszFormat, ... );

#endif // !defined(AFX_WORLDSERVER_H__A8643142_CE71_4A79_A1F3_3EC998E88771__INCLUDED_)
